version: '3'

services:
  web:
    build: docker/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./src/public:/var/www/html/public
    environment:
      TZ: Asia/Tokyo
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - db
    volumes:
      - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
      - ./src/composer.phar:/usr/local/bin/composer
    environment:
      TZ: Asia/Tokyo
  db:
    build: docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tools
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo